<?php

/**
 * @file
 * Records a history of the site's user logins.
 */

/**
 * Implements hook_user_login().
 * The user just logged in.
 *
 * @param $account
 *   The user object on which the operation was just performed.
 */
function login_history_user_login($account) {
  $request = \Drupal::request();
  // @todo Make this work, can we determine what the route is? The one-time
  //   login route is user.reset.
  // Is this a one-time login?
  // $request_array = explode('/', $_GET['q']);
  // if ($request_array[0] == 'user' && isset($request_array[1]) && $request_array[1] == 'reset' && $request_array[5] == 'login') {
  //   $one_time = 1;
  // }
  // else {
  //   $one_time = 0;
  // }
  $one_time = 0;

  // Now save the user's current login timestamp to login_history.
  db_insert('login_history')
    ->fields(array(
      'uid' => $account->id(),
      'login' => $account->getLastLoginTime(),
      'hostname' => $request->getClientIP(),
      'one_time' => $one_time,
      'user_agent' => $request->server->get('HTTP_USER_AGENT'),
    ))
    ->execute();
}

/**
 * Implements hook_menu().
 * Define menu items and page callbacks.
 *
 * @return
 *   An array of menu items.
 */
function login_history_menu() {
  $items = array();
  $items['admin/reports/login-history'] = array(
    'title' => 'Login history',
    'description' => 'Shows previous login information for site users. Useful for troubleshooting and monitoring.',
    'route_name' => 'login_history.report',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function login_history_permission() {
  return array(
    'view own login history' =>  array(
      'title' => t('View own login history'),
    ),
    'view all login histories' =>  array(
      'title' => t('View all login histories'),
    ));
}

function login_history_access_user_history_page($account) {
  return ($account->uid == $GLOBALS['user']->uid && user_access('view own login history')) || user_access('view all login histories');
}

/**
 * Implements hook_block_info().
 */
function login_history_block_info() {
  // Show their last login info.
  $blocks['login_history_last']['info'] = t("Last login");
  $blocks['login_history_last']['properties']['administrative'] = TRUE;
  $blocks['login_history_last']['cache'] = DRUPAL_CACHE_PER_USER;

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function login_history_block_view($delta = '') {
  switch ($delta) {
    case 'login_history_last':
      if (user_is_anonymous()) {
        return;
      }
      // Get information about the user's last login. If no information is
      // found, the block is not displayed.
      if ($last_login = login_history_last_login()) {
        $hostname = $last_login->hostname == ip_address() ? t('this IP address') : $last_login->hostname;
        $user_agent = $last_login->user_agent == $_SERVER['HTTP_USER_AGENT'] ? t('this browser') : $last_login->user_agent;
        $output = '<p>' . t('You last logged in from @hostname using @user_agent.', array('@hostname' => $hostname, '@user_agent' => $user_agent)) . '</p>';
        if (user_access('view own login history')) {
          global $user;
          $output .= '<span class="read-more">' . t('<a href="@link">View your login history.</a>', array('@link' => url('user/'. $user->uid . '/login_history'))) . '</span>';
        }

        $block['subject'] = t('Last login');
        $block['content'] = $output;
        return $block;
      }
  }
}

/**
 * Provide data about the last login for a user.
 *
 * @param $account Optional user object. The only thing that matters is the uid.
 *
 * @return object|false
 *   An object containing information about the last login or FALSE if no
 *   result is found.
 */
function login_history_last_login($account = NULL) {
  if (user_is_anonymous()) {
    return;
  }
  if (empty($account)) {
    global $user;
    $account = $user;
  }
  $last_login = db_query("SELECT login, hostname, one_time, user_agent
                   FROM {login_history}
                   WHERE uid = :uid
                   ORDER BY login DESC
                   LIMIT 1, 2", array(':uid' => $account->uid))->fetchAll();
  return reset($last_login);
}
